import { PERMISSIONS, ROLE_NAMES } from '@itay-chai/contracts';

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLE_NAMES.OWNER]: [PERMISSIONS.SESSION_READ, PERMISSIONS.SESSION_WRITE, PERMISSIONS.TENANT_MANAGE],
  [ROLE_NAMES.STAKEHOLDER]: [PERMISSIONS.SESSION_READ],
  [ROLE_NAMES.CUSTOMER]: [PERMISSIONS.CUSTOMER_WRITE],
  [ROLE_NAMES.OPS_ADMIN]: [
    PERMISSIONS.SESSION_READ,
    PERMISSIONS.SESSION_WRITE,
    PERMISSIONS.BREAK_GLASS,
    PERMISSIONS.DLQ_REPLAY,
  ],
  [ROLE_NAMES.SERVICE]: [PERMISSIONS.SESSION_READ, PERMISSIONS.SESSION_WRITE],
};
