export const COPY = {
  brand: 'איתי חי',
  liveOn: 'מערכת חיה',
  liveOff: 'אין חיבור',
  title: 'הוכחה חיה מול המערכת האמיתית',
  lede: 'לא מצגת. כל שלב מסביר מה רץ, באיזו טבלה זה נשמר במק, ואיך לפתוח קישור ולבדוק. הלקוח יכול לעצור ולבקש לראות את המסד.',
  look: 'דף כל קישורי הבדיקה',
  tables: 'פתח טבלאות Docker',
  run: 'הצג שהמערכת עובדת',
  running: 'רץ מול השרת…',
  score: (passed: number, total: number) => `${passed} מתוך ${total} הוכחות החזיקו`,
  stopped: 'ההוכחה נעצרה. בודקים את השרת ואת העובד.',
  workerMissing: 'המשימה לא הסתיימה. צריך שהשרת, העובד וה־outbox יהיו דולקים.',
  customerSees: 'מה מראים ללקוח',
  inbound: 'צריך החלפת משמרת',
  outbound: 'הבקשה התקבלה',
  chatWaiting: 'אחרי שלב ההודעה תופיע כאן שיחה אמיתית.',
  job: (id: string, status: string) => `משימה ${id} · ${status}`,
  businessA: 'עסק א׳',
  businessB: 'עסק ב׳',
  tenantWaiting: 'עדיין לא בדקנו הפרדה.',
  tenantA: 'הבעלים רואה רק את העסק הזה.',
  tenantB: 'חסום מנתונים של עסק א׳.',
  passed: 'הוכח',
  failed: 'נשבר',
  runningStep: 'עכשיו',
  waiting: 'ממתין',
  completed: 'הושלם',
  reliabilityWaiting: 'תיעוד ואמינות יופיעו אחרי הפרדת העסקים.',
  eventOne: 'אירוע אחד למשימה, יצא לפרסום',
  failureVisible: 'כשל נשאר בבידוד',
  replayed: 'שוחזר עם סיבה כתובה',
  beB: 'תיכנס כעסק ב׳',
  beBRunning: 'נכנס כעסק ב׳…',
  beBTitle: 'אתה עכשיו עסק ב׳',
  beBWaiting: 'תיכנס כעסק השני ותנסה לפתוח את המשימות של עסק א׳. אם ההפרדה עובדת — תיחסם.',
  beBLogin: 'נכנסת כעסק ב׳',
  beBLocked: 'ניסית לפתוח את עסק א׳ — נחסמת',
  beBOwnEmpty: 'השולחן שלך ריק. המשימה של עסק א׳ לא עברה אליך.',
  beBWrite: 'ניסית לשנות משימה של עסק א׳ — נחסמת',
  beBStamp: 'אין גישה',
  aHasJobs: (count: number, id: string) =>
    id ? `${count} משימות אצל עסק א׳, כולל ${id}` : `${count} משימות אצל עסק א׳`,
  phoneLabel: 'וואטסאפ של הלקוח',
  deskA: 'שולחן עסק א׳',
  deskB: 'שולחן עסק ב׳ — אתה',
};

export const STEPS = [
  { id: 'health', title: 'השרת והמסד באמת דולקים' },
  { id: 'login', title: 'שני עסקים נכנסים בנפרד' },
  { id: 'whatsapp', title: 'הודעת לקוח הופכת למשימה' },
  { id: 'duplicate', title: 'אותה הודעה לא יוצרת כפיל' },
  { id: 'isolation-read', title: 'עסק לא רואה עסק אחר' },
  { id: 'isolation-write', title: 'עסק לא משנה עסק אחר' },
  { id: 'ops', title: 'גישת צוות פנימית נעולה' },
  { id: 'event', title: 'כל שינוי מתועד' },
  { id: 'dlq', title: 'כשל נשאר גלוי' },
  { id: 'replay', title: 'אפשר לשחזר עם סיבה' },
] as const;

export const CHAPTERS = [
  { title: 'הלקוח מקבל מענה', ids: ['health', 'login', 'whatsapp', 'duplicate'] },
  { title: 'שני עסקים לא מתערבבים', ids: ['isolation-read', 'isolation-write', 'ops'] },
  { title: 'שום דבר לא נעלם', ids: ['event', 'dlq', 'replay'] },
] as const;
