export const COPY = {
  title: 'הדגמה חיה — יסוד ואמינות',
  lede: 'העמוד הזה מדבר עם המערכת האמיתית. לוחצים על הכפתור ועוברים עם הלקוח על כל הוכחה כשהיא נצבעת בירוק.',
  run: 'הרצת הדגמה חיה',
  running: 'רץ…',
  score: (passed: number, total: number) => `${passed} מתוך ${total} בדיקות עברו`,
  stopped: 'ההדגמה נעצרה.',
  workerMissing: 'המשימה לא הסתיימה. צריך להפעיל את השרת, העובד וה־outbox.',
  customerSees: 'מה הלקוח רואה',
  inbound: 'צריך החלפת משמרת',
  outbound: 'הבקשה התקבלה',
  chatWaiting: 'שיחת הוואטסאפ תופיע כאן אחרי שלב 3.',
  job: (id: string, status: string) => `משימה ${id} · ${status}`,
  businessA: 'עסק א׳',
  businessB: 'עסק ב׳',
  tenantWaiting: 'ממתין לבדיקת ההפרדה.',
  tenantA: 'הבעלים רואה רק את העסק הזה.',
  tenantB: 'חסום מנתונים של עסק א׳.',
  passed: 'עבר',
  failed: 'נכשל',
  runningStep: 'רץ',
  waiting: 'ממתין',
  completed: 'הושלם',
  reliabilityWaiting: 'מעקב האירוע יופיע כאן אחרי שלב 8.',
  eventOne: 'אירוע אחד למשימה',
  failureVisible: 'הכשל בבידוד',
  replayed: 'שוחזר עם סיבה',
};

export const STEPS = [
  { id: 'health', title: 'המערכת חיה' },
  { id: 'login', title: 'שני עסקים מתחברים' },
  { id: 'whatsapp', title: 'הודעת וואטסאפ מטופלת' },
  { id: 'duplicate', title: 'אותה הודעה לא מטופלת פעמיים' },
  { id: 'isolation-read', title: 'עסק לא רואה עסק אחר' },
  { id: 'isolation-write', title: 'עסק לא משנה עסק אחר' },
  { id: 'ops', title: 'גישת חירום פנימית נעולה' },
  { id: 'event', title: 'כל שינוי יוצר אירוע אחד' },
  { id: 'dlq', title: 'כשל נראה ולא נעלם' },
  { id: 'replay', title: 'אפשר לשחזר משימה מהבידוד' },
] as const;
